nics:
  enp37s0:  # ifname
    egress-qos-map:
      5:  # vlan id
        # skb prio : vlan pri
        2: 2
        3: 3
      10:
        2: 2
        3: 3  # For perf test
    tas:
      txtime_delay: 500000
      schedule:
        - time: 300us
          prio: [ 5 ]
        - time: 300000ns
          prio: [ 2, 3 ]
        - time: 400000
          prio: [ -1 ]
    cbs:
      # prio: dict map
      2:
        class: a
        max_frame: 512
        bandwidth: 70000kbps
      3:
        class: b
        max_frame: 512
        bandwidth: 30Mbps
