name: Build

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install clang-format
        run: sudo apt install -qqy --no-install-recommends clang-format
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Flake8
        run: pip install flake8 flake8-import-order
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - name: Linters
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true
          # clippy: true  # Not supported yet
          flake8: true
      - name: Cargo fmt
        uses: actions-rust-lang/rustfmt@v1
      - name: Cargo clippy
        uses: giraffate/clippy-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            driver/QDMA/linux-kernel/scripts
            driver/XDMA/linux-kernel/tests
      - name: Final newline
        uses: Logerfo/newline-action@0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/newline.yml

  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build rust
        run: cargo build --release
