name: Build

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install clang-format
        run: sudo apt install -qqy --no-install-recommends clang-format
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Flake8
        run: pip install flake8 flake8-import-order
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: Linters
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true
          clippy: true
          flake8: true
      - name: Rust lint
        uses: giraffate/clippy-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master

  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-18.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: install build tools
        run: sudo apt install -qqy --no-install-recommends gcc cmake ninja-build
      - name: Checkout
        uses: actions/checkout@master
      - name: build C
        run: |
          mkdir build && cd build
          /usr/bin/cmake -G Ninja -DBUILD_EXAMPLES=ON ..
          /usr/bin/cmake --build .
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build rust
        run: cargo build --release
        working-directory: tsn
